INSERT INTO PRODUCT VALUES (1, 'PRODUCT 1');
INSERT INTO PRODUCT (ID, NAME) VALUES (2, 'PRODUCT 2');
INSERT INTO PRODUCT (ID, NAME) VALUES (3, 'PRODUCT 3');
INSERT INTO PRODUCT (ID, NAME) VALUES (4, 'PRODUCT 4');
INSERT INTO PRODUCT (ID, NAME) VALUES (5, 'PRODUCT 5');
